swagger: '2.0'
info:
  description: APIs protocolos de atendimento
  version: 1.0.0
  title: APIs - Attendencies Start
  termsOfService: 'http://www.nextel.com.br/terms/'
  contact:
    email: IT_Arquitetura@nextel.com.br
host: ms-apis-uat.nextel.com.br
schemes:
  - https
paths:
  '/attendencies_start/V1/':
    post:
      tags:
        - attendencies_start
      summary: cria protocolo de atendimento
      description: |
        API responsável por criar o protocolo de atendimento, pode ser utilizada para atendimento a clientes da base ou para não clientes (prospects)
        <br />
        ###### Exemplo de request para criação de protocolo (cliente da base), com os campos obrigatórios para chamada
        ```json
        {
          "customerId": "7.4408014.10",
          "channel": "M4U"
        }
        ```
        <br />
        ###### Exemplo de request para criação de protocolo prospect (não clientes), com os campos obrigatórios para chamada
        ```json
        {
          "name": "Nome do Cliente",
          "document": "53766528076",
          "phone": "11999998888",
          "channel": "M4U"
        }
        ```
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/AttendenceStart'
      responses:
        '200':
          description: Sucesso
          schema:
            $ref: '#/definitions/Protocol'
        '401':
          description: Não autorizado
          schema:
            $ref: '#/definitions/Unauthorized'
        '450':
          description: Dados não encontrados
          schema:
            $ref: '#/definitions/Error'
        '550':
          description: Erro desconhecido no provedor
          schema:
            $ref: '#/definitions/Error'
      security:
        - attendencies_start: []
securityDefinitions:
  attendencies_start:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/attendencies_start/V1/oauth2/token'
    flow: application
    scopes: {}
definitions:
  AttendenceStart:
    type: object
    properties:
      id:
        description: codigo do protoloco de atendimento
        type: integer
      customerId:
        description: codigo do cliente
        type: string
      externalId:
        description: codigo externo do cliente
        type: string
      name:
        description: nome do cliente ou prospect
        type: string
      document:
        description: documento de identificação, CPF ou CNPJ
        type: string
      phone:
        description: ddd + numero do telefone
        type: string
      channel:
        description: canal de venda
        type: string
      subchannel:
        description: sub canal de venda
        type: string
      description:
        description: descrição do motivo da abertura do atendimento
        type: string
      reason:
        description: motivo do atendimento
        type: string
  Error:
    type: object
    properties:
      message:
        type: string
      detail:
        type: string
      providerDetail:
        $ref: '#/definitions/ProviderDetail'
  Protocol:
    type: object
    description: entidade protocolo de atendimento
    properties:
      id:
        description: codigo do protoloco de atendimento
        type: integer
      date:
        description: data de registro
        type: string
  ProviderDetail:
    type: object
    properties:
      name:
        type: string
      code:
        type: string
      message:
        type: string
  Unauthorized:
    type: object
    properties:
      error_description:
        type: string
        example: The access token is invalid or has expired
      error:
        type: string
        example: invalid_token
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
