swagger: '2.0'
info:
  description: APIs para operacoes referente a clientes
  version: 1.0.0
  title: APIs - Customers
  termsOfService: 'http://www.nextel.com.br/terms/'
  contact:
    email: IT_Arquitetura@nextel.com.br
host: ms-apis-uat.nextel.com.br
tags:
  - name: Invoice
    description: Informacoes de fatura
schemes:
  - https
paths:

  '/customer/invoice/V1':
    put:
      tags:
        - Invoice
      summary: Realiza a confirmacao do pagamento da fatura.
      description: 'Esta API e utilizada para exposicao dos seguintes servicos: 
      
      1) put-bank-slip-payment'
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/CustomerInvoice'
      responses:
        '204':
          description: Sucesso
        '450':
          description: Dados nao encontrados
          schema:
            $ref: '#/definitions/Error'
        '550':
          description: Erro desconhecido no provedor
          schema:
            $ref: '#/definitions/Error'
securityDefinitions:
  
  customers_cpf:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/customers/V1/cpf/cpf/oauth2/token'
    flow: application
    scopes: {}
  nextel_auth:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/customers/V1/billing_mail/oauth2/token'
    flow: application
    scopes:
      billing_mail: consulta e-mail de cobranca do cliente
  installments:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/customers/V1/installments/document/oauth2/token'
    flow: application
    scopes: {}
  customer_hierarchy_V1:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/customer/hierarchy/V1/oauth2/token'
    flow: application
    scopes: {}
  customer_V1_cost_center_V1:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/customer/V1/cost_center/V1/oauth2/token'
    flow: application
    scopes: {}
  customer_V1_contract_information_msisdn:
    type: oauth2
    tokenUrl: 'https://ms-apis-uat.nextel.com.br/customer/V1/contract/information/msisdn/oauth2/token'
    flow: application
    scopes: {}

definitions:

  CustomerInvoice:
    type: object
    required:
      - bankSlipId
      - transactionDate
      - accountingDate
      - externalId
      - id
    properties:
      bankSlipId:
        type: integer
        description: 'PK da fatura'
      transactionDate:
        type: string
        format: date-time
        description: 'Data da transacao'
      accountingDate:
        type: string
        format: date
        description: 'Data contabil'
      externalId:
        type: string
        description: 'NSU da Caixa'
      id:
        type: string
        description: 'NSU do pagamento'
      method:
        $ref: '#/definitions/CustomerInvoiceMethod'
      source:
        $ref: '#/definitions/CustomerInvoiceSource'
  CustomerInvoiceMethod:
    type: object
    description: 'Forma de pagamento'
    properties: 
      id:
        type: string
  CustomerInvoiceSource:
    type: object
    description: 'Origem do pagamento'
    properties: 
      id:
        type: string
  Error:
    type: object
    properties:
      message:
        type: string
      detail:
        type: string
      providerDetail:
        $ref: '#/definitions/ProviderDetail'

  ProviderDetail:
    type: object
    properties:
      name:
        type: string
      code:
        type: string
      message:
        type: string

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'